language: scala
scala:
   - 2.11.8
jdk:
  - oraclejdk8
before_script:
  - psql -c 'create database product_test;' -U postgres
addons:
  postgresql: "9.4"
cache:
  directories:
    - $HOME/.ivy2/cache
env:
  - APPLICATION_SECRET=VERYVERYSECRETYEAH!!! PLAY_PRODUCT_DB_URL=jdbc:postgresql://localhost:5432/product_test PLAY_PRODUCT_DB_USERNAME=postgres PLAY_PRODUCT_DB_PASSWORD= PLAY_PRODUCT_DB_TEST_URL=jdbc:postgresql://localhost:5432/product_test PLAY_PRODUCT_DB_TEST_USERNAME=postgres PLAY_PRODUCT_DB_TEST_PASSWORD=